name: Update demo website plugin
env:
  DEMODEPLOY_COMMAND: ${{ secrets.DEMODEPLOY_COMMAND }}
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Generate Deploy Key
        run: 'echo "$DEPLOYKEY" > id_rsa ; chmod 400 id_rsa'
        shell: bash
        env:
          DEPLOYKEY: ${{secrets.DEPLOYKEY}}

      - name: Run Simple Deploy
        shell: bash
        run: "$DEMODEPLOY_COMMAND \
         -i ./id_rsa \
         -o StrictHostKeyChecking=no \
         'cd /home/dev/sites/magento ; \
         composer update bloomreach/bloomreach-engagement-connector-magento:dev-develop ; \
         bin/magento setup:upgrade ; \
         bin/magento deploy:mode:set production'"
