name: Update packagist
env:
  WEBHOOK: ${{ secrets.WEBHOOK }}
on:
  push:
    branches:
      - develop
  
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Run webhook
        shell: bash
        run: "$WEBHOOK"
